### ISSUE TITLE
Confuse about commands running multiple cameras with multiple patterns

### ISSUE THREAD

**Issue by zhaozhongch** [oliver-batchelor/multical#21]
I tried to run single camera with single calibration pattern successfully with the following command
```
multical calibrate --boards aprilgrid_6x6.yaml --cameras cam1 --camera_pattern 'data/{camera}'
```
I put my calibration image into 
```
- data
  - cam1
     - im0.png
     - im1.png
     - im2.png
     - ...
```
The yaml file is 
```
boards:
  aprilgrid_9x9:
    _type_: 'aprilgrid'
    size: [6, 6]
    tag_family: t36h11 # ['t16h5', 't25h7', 't25h9', 't36h11']
    tag_length: 0.06
    tag_spacing: 0.3

    min_rows: 2
    min_points: 12
```
Now I want to extend to two cameras, two patterns
I change the data folder as the following, assume in each image I have two patterns can be seen
```
- data
  - cam1
     - im0.png
     - im1.png
     - im2.png
     - ...
   - cam2
     - im0.png
     - im1.png
     - im2.png
     - ...     
```
Yaml file `aprilgrid_multiple.yaml`
```
boards:
  aprilgrid_0:
    _type_: 'aprilgrid'
    tag_length: 0.07
    tag_spacing: 0.25
    size: [6, 6]
    start_id: 0
    min_rows: 2
    min_points: 12
  aprilgrid_1:
    _type_: 'aprilgrid'
    tag_length: 0.07
    tag_spacing: 0.25
    size: [6, 6]
    start_id: 48 # Start from different ID on different board
    min_rows: 2
    min_points: 12
```
From the instruction in the Readme and my understanding, I should run the commands as following
```
multical calibrate --boards aprilgrid_multiple.yaml --cameras cam1,cam2 --camera_pattern 'data/{camera}'
```
However, this command shows error 
```
....
[Errno 2] No such file or directory: './data/cam1,cam2'
```
Looks it tries to look for a folder names `cam1,cam2` instead of `cam1` and `cam2`. Is this a bug or do I misunderstand how to input multiple cameras?
Another question is, I am not sure how the library can distinguish two patterns in the image. I assume the `start_id` in the yaml file is used know different patterns but does that mean we should write an ID (like 0, 48) name on the pattern? Sorry, this question may sound naive but I am indeed not sure if it can just automatically detect two patterns and won't mix them up. 
Thanks in advance
